jobs:
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run format:check && npm test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
